#############################################################################
# Makefile for building: Virtual-Library
# Generated by qmake (3.1) (Qt 5.15.3)
# Project:  Virtual-Library.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile Virtual-Library.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -std=gnu++11 -Wall -Wextra -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -Isrc/Logic\ Model -Isrc/Save/xml -Isrc/Save/json -ITest/XmlTests -Isrc/GUI -Isrc/GUI/MainDisplay -Isrc/Save -Isrc/GUI/Menu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = Virtual-Library1.0.0
DISTDIR = /home/kevin/Desktop/OOProject/Virtual-Library/.tmp/Virtual-Library1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Xml.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/GUI/MainWindow.cpp \
		src/GUI/MainDisplay/ScrollPanel.cpp \
		src/GUI/MainDisplay/CustomScrollArea.cpp \
		src/GUI/LoadVisitor.cpp \
		src/GUI/MainDisplay/MainDisplay.cpp \
		src/GUI/MainDisplay/ButtonWidget.cpp \
		src/GUI/Menu/TopMenu.cpp \
		src/GUI/SearchBar.cpp \
		src/GUI/MainDisplay/ScrollWidget.cpp \
		src/Logic\ Model/MediaItem.cpp \
		src/Logic\ Model/AudioVisual.cpp \
		src/Logic\ Model/Readable.cpp \
		src/Logic\ Model/Article.cpp \
		src/Logic\ Model/Book.cpp \
		src/Logic\ Model/Film.cpp \
		src/Logic\ Model/Music.cpp \
		src/Logic\ Model/Podcast.cpp \
		Test/XmlTests/XmlManagerTest.cpp \
		src/Save/json/JsonVisitor.cpp \
		src/Save/xml/XmlVisitor.cpp \
		src/Save/xml/XmlManager.cpp \
		src/Save/json/JsonManager.cpp \
		src/Save/xml/XmlReader.cpp \
		src/Save/ManagerFactory.cpp \
		Test/JsonTests/JsonTest.cpp \
		Test/GUITests/MainWindowTests/LoadFromFileTests.cpp \
		src/main.cpp moc_MainWindow.cpp \
		moc_ScrollPanel.cpp \
		moc_MainDisplay.cpp \
		moc_ButtonWidget.cpp \
		moc_TopMenu.cpp \
		moc_SearchBar.cpp \
		moc_ScrollWidget.cpp
OBJECTS       = MainWindow.o \
		ScrollPanel.o \
		CustomScrollArea.o \
		LoadVisitor.o \
		MainDisplay.o \
		ButtonWidget.o \
		TopMenu.o \
		SearchBar.o \
		ScrollWidget.o \
		MediaItem.o \
		AudioVisual.o \
		Readable.o \
		Article.o \
		Book.o \
		Film.o \
		Music.o \
		Podcast.o \
		XmlManagerTest.o \
		JsonVisitor.o \
		XmlVisitor.o \
		XmlManager.o \
		JsonManager.o \
		XmlReader.o \
		ManagerFactory.o \
		JsonTest.o \
		LoadFromFileTests.o \
		main.o \
		moc_MainWindow.o \
		moc_ScrollPanel.o \
		moc_MainDisplay.o \
		moc_ButtonWidget.o \
		moc_TopMenu.o \
		moc_SearchBar.o \
		moc_ScrollWidget.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Virtual-Library.pro src/GUI/MainWindow.h \
		src/GUI/MainDisplay/ScrollPanel.h \
		src/GUI/MainDisplay/CustomScrollArea.h \
		src/GUI/LoadVisitor.h \
		src/GUI/MainDisplay/MainDisplay.h \
		src/GUI/MainDisplay/ButtonWidget.h \
		src/GUI/Menu/TopMenu.h \
		src/GUI/SearchBar.h \
		src/GUI/MainDisplay/ScrollWidget.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Readable.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/Book.h \
		src/Logic\ Model/Film.h \
		src/Logic\ Model/Article.h \
		src/Logic\ Model/Music.h \
		src/Logic\ Model/Podcast.h \
		src/Save/json/JsonVisitor.h \
		Test/XmlTests/XmlManagerTest.h \
		src/Logic\ Model/Visitor.h \
		src/Save/xml/XmlVisitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/Save/json/JsonManager.h \
		src/Save/FileManager.h \
		src/Save/ManagerFactory.h \
		src/Save/xml/XmlReader.h \
		src/Save/xml/XmlManager.h \
		Test/JsonTests/JsonTest.h \
		Test/GUITests/MainWindowTests/LoadFromFileTests.h src/GUI/MainWindow.cpp \
		src/GUI/MainDisplay/ScrollPanel.cpp \
		src/GUI/MainDisplay/CustomScrollArea.cpp \
		src/GUI/LoadVisitor.cpp \
		src/GUI/MainDisplay/MainDisplay.cpp \
		src/GUI/MainDisplay/ButtonWidget.cpp \
		src/GUI/Menu/TopMenu.cpp \
		src/GUI/SearchBar.cpp \
		src/GUI/MainDisplay/ScrollWidget.cpp \
		src/Logic\ Model/MediaItem.cpp \
		src/Logic\ Model/AudioVisual.cpp \
		src/Logic\ Model/Readable.cpp \
		src/Logic\ Model/Article.cpp \
		src/Logic\ Model/Book.cpp \
		src/Logic\ Model/Film.cpp \
		src/Logic\ Model/Music.cpp \
		src/Logic\ Model/Podcast.cpp \
		Test/XmlTests/XmlManagerTest.cpp \
		src/Save/json/JsonVisitor.cpp \
		src/Save/xml/XmlVisitor.cpp \
		src/Save/xml/XmlManager.cpp \
		src/Save/json/JsonManager.cpp \
		src/Save/xml/XmlReader.cpp \
		src/Save/ManagerFactory.cpp \
		Test/JsonTests/JsonTest.cpp \
		Test/GUITests/MainWindowTests/LoadFromFileTests.cpp \
		src/main.cpp
QMAKE_TARGET  = Virtual-Library
DESTDIR       = 
TARGET        = Virtual-Library


first: all
####### Build rules

Virtual-Library:  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Virtual-Library.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		Virtual-Library.pro
	$(QMAKE) -o Makefile Virtual-Library.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
Virtual-Library.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile Virtual-Library.pro

qmake_all: FORCE


all: Makefile Virtual-Library

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/GUI/MainWindow.h src/GUI/MainDisplay/ScrollPanel.h src/GUI/MainDisplay/CustomScrollArea.h src/GUI/LoadVisitor.h src/GUI/MainDisplay/MainDisplay.h src/GUI/MainDisplay/ButtonWidget.h src/GUI/Menu/TopMenu.h src/GUI/SearchBar.h src/GUI/MainDisplay/ScrollWidget.h src/Logic\ Model/MediaItem.h src/Logic\ Model/Readable.h src/Logic\ Model/AudioVisual.h src/Logic\ Model/Book.h src/Logic\ Model/Film.h src/Logic\ Model/Article.h src/Logic\ Model/Music.h src/Logic\ Model/Podcast.h src/Save/json/JsonVisitor.h Test/XmlTests/XmlManagerTest.h src/Logic\ Model/Visitor.h src/Save/xml/XmlVisitor.h src/Logic\ Model/ConstVisitor.h src/Save/json/JsonManager.h src/Save/FileManager.h src/Save/ManagerFactory.h src/Save/xml/XmlReader.h src/Save/xml/XmlManager.h Test/JsonTests/JsonTest.h Test/GUITests/MainWindowTests/LoadFromFileTests.h $(DISTDIR)/
	$(COPY_FILE) --parents src/GUI/MainWindow.cpp src/GUI/MainDisplay/ScrollPanel.cpp src/GUI/MainDisplay/CustomScrollArea.cpp src/GUI/LoadVisitor.cpp src/GUI/MainDisplay/MainDisplay.cpp src/GUI/MainDisplay/ButtonWidget.cpp src/GUI/Menu/TopMenu.cpp src/GUI/SearchBar.cpp src/GUI/MainDisplay/ScrollWidget.cpp src/Logic\ Model/MediaItem.cpp src/Logic\ Model/AudioVisual.cpp src/Logic\ Model/Readable.cpp src/Logic\ Model/Article.cpp src/Logic\ Model/Book.cpp src/Logic\ Model/Film.cpp src/Logic\ Model/Music.cpp src/Logic\ Model/Podcast.cpp Test/XmlTests/XmlManagerTest.cpp src/Save/json/JsonVisitor.cpp src/Save/xml/XmlVisitor.cpp src/Save/xml/XmlManager.cpp src/Save/json/JsonManager.cpp src/Save/xml/XmlReader.cpp src/Save/ManagerFactory.cpp Test/JsonTests/JsonTest.cpp Test/GUITests/MainWindowTests/LoadFromFileTests.cpp src/main.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -std=gnu++11 -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_MainWindow.cpp moc_ScrollPanel.cpp moc_MainDisplay.cpp moc_ButtonWidget.cpp moc_TopMenu.cpp moc_SearchBar.cpp moc_ScrollWidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_MainWindow.cpp moc_ScrollPanel.cpp moc_MainDisplay.cpp moc_ButtonWidget.cpp moc_TopMenu.cpp moc_SearchBar.cpp moc_ScrollWidget.cpp
moc_MainWindow.cpp: src/GUI/MainWindow.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/GUI/MainDisplay/ScrollPanel.h \
		src/GUI/MainDisplay/CustomScrollArea.h \
		src/GUI/MainDisplay/ButtonWidget.h \
		src/Save/FileManager.h \
		src/GUI/MainDisplay/MainDisplay.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kevin/Desktop/OOProject/Virtual-Library/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kevin/Desktop/OOProject/Virtual-Library -I'/home/kevin/Desktop/OOProject/Virtual-Library/src/Logic Model' -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save/xml -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save/json -I/home/kevin/Desktop/OOProject/Virtual-Library/Test/XmlTests -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI/MainDisplay -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI/Menu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/GUI/MainWindow.h -o moc_MainWindow.cpp

moc_ScrollPanel.cpp: src/GUI/MainDisplay/ScrollPanel.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kevin/Desktop/OOProject/Virtual-Library/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kevin/Desktop/OOProject/Virtual-Library -I'/home/kevin/Desktop/OOProject/Virtual-Library/src/Logic Model' -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save/xml -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save/json -I/home/kevin/Desktop/OOProject/Virtual-Library/Test/XmlTests -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI/MainDisplay -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI/Menu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/GUI/MainDisplay/ScrollPanel.h -o moc_ScrollPanel.cpp

moc_MainDisplay.cpp: src/GUI/MainDisplay/MainDisplay.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kevin/Desktop/OOProject/Virtual-Library/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kevin/Desktop/OOProject/Virtual-Library -I'/home/kevin/Desktop/OOProject/Virtual-Library/src/Logic Model' -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save/xml -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save/json -I/home/kevin/Desktop/OOProject/Virtual-Library/Test/XmlTests -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI/MainDisplay -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI/Menu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/GUI/MainDisplay/MainDisplay.h -o moc_MainDisplay.cpp

moc_ButtonWidget.cpp: src/GUI/MainDisplay/ButtonWidget.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kevin/Desktop/OOProject/Virtual-Library/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kevin/Desktop/OOProject/Virtual-Library -I'/home/kevin/Desktop/OOProject/Virtual-Library/src/Logic Model' -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save/xml -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save/json -I/home/kevin/Desktop/OOProject/Virtual-Library/Test/XmlTests -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI/MainDisplay -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI/Menu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/GUI/MainDisplay/ButtonWidget.h -o moc_ButtonWidget.cpp

moc_TopMenu.cpp: src/GUI/Menu/TopMenu.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kevin/Desktop/OOProject/Virtual-Library/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kevin/Desktop/OOProject/Virtual-Library -I'/home/kevin/Desktop/OOProject/Virtual-Library/src/Logic Model' -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save/xml -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save/json -I/home/kevin/Desktop/OOProject/Virtual-Library/Test/XmlTests -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI/MainDisplay -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI/Menu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/GUI/Menu/TopMenu.h -o moc_TopMenu.cpp

moc_SearchBar.cpp: src/GUI/SearchBar.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kevin/Desktop/OOProject/Virtual-Library/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kevin/Desktop/OOProject/Virtual-Library -I'/home/kevin/Desktop/OOProject/Virtual-Library/src/Logic Model' -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save/xml -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save/json -I/home/kevin/Desktop/OOProject/Virtual-Library/Test/XmlTests -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI/MainDisplay -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI/Menu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/GUI/SearchBar.h -o moc_SearchBar.cpp

moc_ScrollWidget.cpp: src/GUI/MainDisplay/ScrollWidget.h \
		src/GUI/MainDisplay/CustomScrollArea.h \
		src/GUI/MainDisplay/ButtonWidget.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/GUI/MainDisplay/ScrollPanel.h \
		moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/kevin/Desktop/OOProject/Virtual-Library/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/kevin/Desktop/OOProject/Virtual-Library -I'/home/kevin/Desktop/OOProject/Virtual-Library/src/Logic Model' -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save/xml -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save/json -I/home/kevin/Desktop/OOProject/Virtual-Library/Test/XmlTests -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI/MainDisplay -I/home/kevin/Desktop/OOProject/Virtual-Library/src/Save -I/home/kevin/Desktop/OOProject/Virtual-Library/src/GUI/Menu -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtXml -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/include/c++/11 -I/usr/include/x86_64-linux-gnu/c++/11 -I/usr/include/c++/11/backward -I/usr/lib/gcc/x86_64-linux-gnu/11/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/GUI/MainDisplay/ScrollWidget.h -o moc_ScrollWidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

MainWindow.o: src/GUI/MainWindow.cpp src/GUI/MainWindow.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/GUI/MainDisplay/ScrollPanel.h \
		src/GUI/MainDisplay/CustomScrollArea.h \
		src/GUI/MainDisplay/ButtonWidget.h \
		src/Save/FileManager.h \
		src/GUI/MainDisplay/MainDisplay.h \
		src/Save/xml/XmlManager.h \
		src/GUI/SearchBar.h \
		src/GUI/Menu/TopMenu.h \
		src/Save/ManagerFactory.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainWindow.o src/GUI/MainWindow.cpp

ScrollPanel.o: src/GUI/MainDisplay/ScrollPanel.cpp src/GUI/MainDisplay/ScrollPanel.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/GUI/MainDisplay/ButtonWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScrollPanel.o src/GUI/MainDisplay/ScrollPanel.cpp

CustomScrollArea.o: src/GUI/MainDisplay/CustomScrollArea.cpp src/GUI/MainDisplay/CustomScrollArea.h \
		src/GUI/MainDisplay/ButtonWidget.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o CustomScrollArea.o src/GUI/MainDisplay/CustomScrollArea.cpp

LoadVisitor.o: src/GUI/LoadVisitor.cpp src/GUI/LoadVisitor.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/ConstVisitor.h \
		src/Logic\ Model/Readable.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/Article.h \
		src/Logic\ Model/Book.h \
		src/Logic\ Model/Film.h \
		src/Logic\ Model/Podcast.h \
		src/Logic\ Model/Music.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoadVisitor.o src/GUI/LoadVisitor.cpp

MainDisplay.o: src/GUI/MainDisplay/MainDisplay.cpp src/GUI/MainDisplay/MainDisplay.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/GUI/MainDisplay/ScrollPanel.h \
		src/GUI/MainDisplay/CustomScrollArea.h \
		src/GUI/MainDisplay/ButtonWidget.h \
		src/GUI/LoadVisitor.h \
		src/Logic\ Model/Readable.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/Article.h \
		src/Logic\ Model/Book.h \
		src/Logic\ Model/Film.h \
		src/Logic\ Model/Podcast.h \
		src/Logic\ Model/Music.h \
		src/GUI/MainDisplay/ScrollWidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MainDisplay.o src/GUI/MainDisplay/MainDisplay.cpp

ButtonWidget.o: src/GUI/MainDisplay/ButtonWidget.cpp src/GUI/MainDisplay/ButtonWidget.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ButtonWidget.o src/GUI/MainDisplay/ButtonWidget.cpp

TopMenu.o: src/GUI/Menu/TopMenu.cpp src/GUI/Menu/TopMenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o TopMenu.o src/GUI/Menu/TopMenu.cpp

SearchBar.o: src/GUI/SearchBar.cpp src/GUI/SearchBar.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o SearchBar.o src/GUI/SearchBar.cpp

ScrollWidget.o: src/GUI/MainDisplay/ScrollWidget.cpp src/GUI/MainDisplay/ScrollWidget.h \
		src/GUI/MainDisplay/CustomScrollArea.h \
		src/GUI/MainDisplay/ButtonWidget.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/GUI/MainDisplay/ScrollPanel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ScrollWidget.o src/GUI/MainDisplay/ScrollWidget.cpp

MediaItem.o: src/Logic\ Model/MediaItem.cpp src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o MediaItem.o src/Logic\ Model/MediaItem.cpp

AudioVisual.o: src/Logic\ Model/AudioVisual.cpp src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o AudioVisual.o src/Logic\ Model/AudioVisual.cpp

Readable.o: src/Logic\ Model/Readable.cpp src/Logic\ Model/Readable.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Readable.o src/Logic\ Model/Readable.cpp

Article.o: src/Logic\ Model/Article.cpp src/Logic\ Model/Article.h \
		src/Logic\ Model/Readable.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Article.o src/Logic\ Model/Article.cpp

Book.o: src/Logic\ Model/Book.cpp src/Logic\ Model/Book.h \
		src/Logic\ Model/Readable.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Book.o src/Logic\ Model/Book.cpp

Film.o: src/Logic\ Model/Film.cpp src/Logic\ Model/Film.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Film.o src/Logic\ Model/Film.cpp

Music.o: src/Logic\ Model/Music.cpp src/Logic\ Model/Music.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Music.o src/Logic\ Model/Music.cpp

Podcast.o: src/Logic\ Model/Podcast.cpp src/Logic\ Model/Podcast.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o Podcast.o src/Logic\ Model/Podcast.cpp

XmlManagerTest.o: Test/XmlTests/XmlManagerTest.cpp src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/Logic\ Model/Book.h \
		src/Logic\ Model/Readable.h \
		src/Logic\ Model/Article.h \
		src/Logic\ Model/Film.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/Podcast.h \
		src/Logic\ Model/Music.h \
		Test/XmlTests/XmlManagerTest.h \
		src/Save/xml/XmlManager.h \
		src/Save/FileManager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XmlManagerTest.o Test/XmlTests/XmlManagerTest.cpp

JsonVisitor.o: src/Save/json/JsonVisitor.cpp src/Save/json/JsonVisitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/Readable.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/Article.h \
		src/Logic\ Model/Book.h \
		src/Logic\ Model/Film.h \
		src/Logic\ Model/Podcast.h \
		src/Logic\ Model/Music.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JsonVisitor.o src/Save/json/JsonVisitor.cpp

XmlVisitor.o: src/Save/xml/XmlVisitor.cpp src/Save/xml/XmlVisitor.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/Logic\ Model/Readable.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/Article.h \
		src/Logic\ Model/Book.h \
		src/Logic\ Model/Film.h \
		src/Logic\ Model/Podcast.h \
		src/Logic\ Model/Music.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XmlVisitor.o src/Save/xml/XmlVisitor.cpp

XmlManager.o: src/Save/xml/XmlManager.cpp src/Save/xml/XmlManager.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/Save/FileManager.h \
		src/Save/xml/XmlReader.h \
		src/Logic\ Model/Readable.h \
		src/Logic\ Model/Book.h \
		src/Logic\ Model/Article.h \
		src/Logic\ Model/Film.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/Music.h \
		src/Logic\ Model/Podcast.h \
		src/Save/xml/XmlVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XmlManager.o src/Save/xml/XmlManager.cpp

JsonManager.o: src/Save/json/JsonManager.cpp src/Save/json/JsonManager.h \
		src/Logic\ Model/Article.h \
		src/Logic\ Model/Readable.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/Logic\ Model/Book.h \
		src/Logic\ Model/Film.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/Music.h \
		src/Logic\ Model/Podcast.h \
		src/Save/FileManager.h \
		src/Save/json/JsonVisitor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JsonManager.o src/Save/json/JsonManager.cpp

XmlReader.o: src/Save/xml/XmlReader.cpp src/Save/xml/XmlReader.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/Logic\ Model/Readable.h \
		src/Logic\ Model/Book.h \
		src/Logic\ Model/Article.h \
		src/Logic\ Model/Film.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/Music.h \
		src/Logic\ Model/Podcast.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o XmlReader.o src/Save/xml/XmlReader.cpp

ManagerFactory.o: src/Save/ManagerFactory.cpp src/Save/ManagerFactory.h \
		src/Save/FileManager.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/Save/xml/XmlManager.h \
		src/Save/json/JsonManager.h \
		src/Logic\ Model/Article.h \
		src/Logic\ Model/Readable.h \
		src/Logic\ Model/Book.h \
		src/Logic\ Model/Film.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/Music.h \
		src/Logic\ Model/Podcast.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ManagerFactory.o src/Save/ManagerFactory.cpp

JsonTest.o: Test/JsonTests/JsonTest.cpp src/Save/json/JsonManager.h \
		src/Logic\ Model/Article.h \
		src/Logic\ Model/Readable.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/Logic\ Model/Book.h \
		src/Logic\ Model/Film.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/Music.h \
		src/Logic\ Model/Podcast.h \
		src/Save/FileManager.h \
		Test/JsonTests/JsonTest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o JsonTest.o Test/JsonTests/JsonTest.cpp

LoadFromFileTests.o: Test/GUITests/MainWindowTests/LoadFromFileTests.cpp Test/GUITests/MainWindowTests/LoadFromFileTests.h \
		src/GUI/LoadVisitor.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/ConstVisitor.h \
		src/Logic\ Model/Readable.h \
		src/Logic\ Model/AudioVisual.h \
		src/Logic\ Model/Article.h \
		src/Logic\ Model/Book.h \
		src/Logic\ Model/Film.h \
		src/Logic\ Model/Podcast.h \
		src/Logic\ Model/Music.h \
		src/Save/json/JsonManager.h \
		src/Save/FileManager.h \
		src/Save/xml/XmlManager.h \
		Test/XmlTests/XmlManagerTest.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LoadFromFileTests.o Test/GUITests/MainWindowTests/LoadFromFileTests.cpp

main.o: src/main.cpp src/GUI/MainWindow.h \
		src/Logic\ Model/MediaItem.h \
		src/Logic\ Model/Visitor.h \
		src/Logic\ Model/ConstVisitor.h \
		src/GUI/MainDisplay/ScrollPanel.h \
		src/GUI/MainDisplay/CustomScrollArea.h \
		src/GUI/MainDisplay/ButtonWidget.h \
		src/Save/FileManager.h \
		src/GUI/MainDisplay/MainDisplay.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o src/main.cpp

moc_MainWindow.o: moc_MainWindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainWindow.o moc_MainWindow.cpp

moc_ScrollPanel.o: moc_ScrollPanel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ScrollPanel.o moc_ScrollPanel.cpp

moc_MainDisplay.o: moc_MainDisplay.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_MainDisplay.o moc_MainDisplay.cpp

moc_ButtonWidget.o: moc_ButtonWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ButtonWidget.o moc_ButtonWidget.cpp

moc_TopMenu.o: moc_TopMenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_TopMenu.o moc_TopMenu.cpp

moc_SearchBar.o: moc_SearchBar.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_SearchBar.o moc_SearchBar.cpp

moc_ScrollWidget.o: moc_ScrollWidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ScrollWidget.o moc_ScrollWidget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

